[ports]
# Collector
collector-host-port="0.0.0.0:14267"
# Agent ports
http_server-host-port=5778
processor_zipkin_compact-server-host-port=5775
processor_jaeger_compact-server-host-port=6831
processor_jaeger_binary-server-host-port=6832
